// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  angular.module('News', []);

  angular.module('News').factory('Controller', function() {
    var Controller;
    return Controller = (function() {

      function Controller() {}

      return Controller;

    })();
  });

  angular.module('News').controller('FeedController', [
    'Controller', '$scope', function(Controller, $scope) {
      var FeedController;
      FeedController = (function(_super) {

        __extends(FeedController, _super);

        function FeedController($scope) {
          this.$scope = $scope;
        }

        return FeedController;

      })(Controller);
      return new FeedController($scope);
    }
  ]);

  angular.module('News').controller('ItemController', [
    'Controller', '$scope', function(Controller, $scope) {
      var ItemController;
      ItemController = (function(_super) {

        __extends(ItemController, _super);

        function ItemController($scope) {
          this.$scope = $scope;
        }

        return ItemController;

      })(Controller);
      return new ItemController($scope);
    }
  ]);

  angular.module('News').factory([
    'Model', function(Model) {
      var ItemModel;
      return ItemModel = (function(_super) {

        __extends(ItemModel, _super);

        function ItemModel() {
          return ItemModel.__super__.constructor.apply(this, arguments);
        }

        return ItemModel;

      })(Model);
    }
  ]);

  angular.module('News').factory('Model', function() {
    var Model;
    return Model = (function() {

      function Model() {}

      return Model;

    })();
  });

  angular.module('News').factory([
    'Model', function(Model) {
      var FeedModel;
      return FeedModel = (function(_super) {

        __extends(FeedModel, _super);

        function FeedModel() {
          return FeedModel.__super__.constructor.apply(this, arguments);
        }

        return FeedModel;

      })(Model);
    }
  ]);

  angular.module('News').factory([
    'Model', function(Model) {
      var FeedModel;
      return FeedModel = (function(_super) {

        __extends(FeedModel, _super);

        function FeedModel() {
          return FeedModel.__super__.constructor.apply(this, arguments);
        }

        return FeedModel;

      })(Model);
    }
  ]);

}).call(this);
